services:
  # postgres:
  #   container_name: postgres
  #   image: postgres:11.5-alpine
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=zone@123
  #     - POSTGRES_DB=plm_automation

  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  # pgadmin4:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   restart: always
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@mail.com
  #     - PGADMIN_DEFAULT_PASSWORD=password

  # zookeeper:
  #   image: 'zookeeper:3.7.0'
  #   ports:
  #     - '2181:2181'
  # kafka:
  #   image: 'confluentinc/cp-kafka:6.2.0'
  #   ports:
  #     - '9092:9092'
  #   environment:
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   depends_on:
  #     - zookeeper

  # mongo:
  #   image: mongo:latest
  #   container_name: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./data:/data/db
